import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import CryptoSale from "./components/Cryptosale";
import Card from "./components/Card";
import Footer from "./components/Footer";
import Treasury from "./components/treasure";
import Section from "./components/Section";
import Userexp from "./components/Userexp";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "KrizPay",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className={inter.className}>
      <Navbar/>

        <div className="min-h-screen">{children}
       
     
        <CryptoSale/>
        <Treasury/>
        <Section/>
        <Userexp/>
        <Footer />
        </div>
     
      </body>
    </html>
  );
}
